---
- name: install utility softwares
  become: yes
  hosts: appserver
  tasks: 
    - name: install packages
      package: 
        name: "{{ item }}"
        state: present 
      loop: "{{ packages }}"