---
- name: Spring boot depoy
  hosts: appserver
  become: yes
  tasks:
    - name: fail if other distrubution
      fail:
        msg: "This is not Ubuntu or CentOS dist"
      when: ansible_distribution != "Ubuntu"  and ansible_distribution != "CentOS"
    - name: install packages
      Package: 
        name: "{{ java_package }}"
        state: present
      notify:
        - debug message for java
    - name: adding springboot user
      user:
        name: "{{ app_user }}" 
        password: "{{ app_user }}"
        state: present       
    - name: make directory
      file: 
        path: "{{ app_dir }}"
        state: directory
      notify: 
        - debug message for directory creation
    - name: download application
      get_url:
        url: "{{ download_app }}"
        dest: "{{ app_file }}"
    - name: Necesary permissions to a file
      file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: "{{ app_user }}"
        mode: '500'
        state: file
    - name: copying service file
      copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: systemctl commands 
      systemd:
        name: 'springpetclinic'
        daemon_reload: yes
        enabled: yes
        state: 'started'
  handlers:
    - name: debug message for java
      debug:
        msg: "java with package {{ java_package }} is installed"

    - name: debug message for directory creation
      debug:
        msg: "Directory created at {{ app_dir }}"